name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'repository_dispatch'
        run: |
          echo "event_name: '${{ github.event_name }}'"
          echo "event.action: '${{ github.event.action }}'"
          echo "event.client_payload.repo: '${{ github.event.client_payload.repo }}'"
          echo "event.client_payload.commit_sha: '${{ github.event.client_payload.commit_sha }}'"
          echo "event.client_payload.maturity: '${{ github.event.client_payload.maturity }}'"
          echo "event.client_payload.version: '${{ github.event.client_payload.version }}'"
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # - run: |
      #     git clone --depth 1 \
      #       "https://${{ secrets.ACCESS_TOKEN }}@github.com/${{ env.UPSTREAM_REPO }}" \
      #       ${{ env.UPSTREAM_CLONE_DIR }}
