name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        if: github.event_name == 'repository_dispatch'
        run: |
          echo "event_name: '${{ github.event_name }}'"
          echo "event.action: '${{ github.event.action }}'"
          echo "event.client_payload.commit_sha: '${{ github.event.client_payload.commit_sha }}'"
          echo "event.client_payload.maturity: '${{ github.event.client_payload.maturity }}'"
          echo "event.client_payload.version: '${{ github.event.client_payload.version }}'"
